### ISSUE TITLE
state enum excludes "Offline after error"

### ISSUE THREAD

**Issue by lnjustin** [mikec85/hubitatdrivers#6]
I'm trying to set up a rule machine rule based on the printer's state, but there is no option to select "Offline after error", which appears to  be the state after shutting power off to the printer. Is there a way to account for this "Offline after error" state, either by adding that state to the enum, or by having the state be either just "offline" or "error" (offline preferable probably).

**Comment by mikec85** [comment]
Added, can update via hubitat package manager
